version: '3'
services:
  ranger:
    build:
      context: .
      dockerfile: Dockerfile.ranger
      args:
        - RANGER_VERSION=${RANGER_VERSION}
        - RANGER_DB_TYPE=${RANGER_DB_TYPE}
        - RANGER_ADMIN_JAVA_VERSION=${RANGER_ADMIN_JAVA_VERSION}
    image: ranger:latest
    container_name: ranger
    hostname: ranger.example.com
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "6080:6080"
      - "16080:16080"
    depends_on:
      ranger-zk:
        condition: service_started
      ranger-db:
        condition: service_healthy
      ranger-solr:
        condition: service_started
#      ranger-elasticsearch:
#        condition: service_started
    environment:
      - RANGER_VERSION
      - RANGER_DB_TYPE
      - DEBUG_ADMIN=${DEBUG_ADMIN:-false}
      - REMOTE_JVM_DEBUG=${REMOTE_JVM_DEBUG:-false}
    volumes:
      - /var/log/ranger:/var/log/ranger
    command:
      - /home/ranger/scripts/ranger.sh

#  ranger-elasticsearch:
#    image: elasticsearch:7.17.24
#    container_name: ranger-elasticsearch
#    hostname: ranger-elasticsearch.example.com
#    environment:
#      - discovery.type=single-node
#      - http.host=0.0.0.0
#      - xpack.security.enabled=false
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
#    networks:
#      - ranger
#    ports:
#      - "9200:9200"

  ranger-zk:
    build:
      context: .
      dockerfile: Dockerfile.ranger-zk
      args:
        - ZK_VERSION=${ZK_VERSION}
    image: ranger-zk
    container_name: ranger-zk
    hostname: ranger-zk.example.com
    networks:
      - ranger
    ports:
      - "2181:2181"

  ranger-solr:
    build:
      context: .
      dockerfile: Dockerfile.ranger-solr
      args:
        - SOLR_VERSION=${SOLR_VERSION}
    image: ranger-solr
    container_name: ranger-solr
    hostname: ranger-solr.example.com
    networks:
      - ranger
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - ranger_audits
      - /opt/solr/server/solr/configsets/ranger_audits/

volumes:
  esdata:

networks:
  ranger:
    name: rangernw
